### ISSUE TITLE
Running 'npm test' results in "Test suite failed to run" on "src/ethereum/nation.test.js" and others

### ISSUE THREAD

**Issue by Mnuzz** [Bit-Nation/BITNATION-Pangea-libs#53]
## Problem / Task
> Describe the task that need's to be done / the problem as good as possible. 

running `npm test` on the `develop` branch should always succeed.

This is the output I am seeing:
```

No errors!
 PASS  src/profile/profile.test.js
 PASS  src/ethereum/PangeaProvider.test.js
 PASS  src/ethereum/utils.test.js
 PASS  src/ethereum/web3.test.js
 PASS  src/test_implementations/nodeJsSecureStorage.test.js
 FAIL  src/ethereum/nation.test.js
  ● Test suite failed to run

    TypeError: Cannot redefine property: Worker
        at Function.defineProperty (native)
      
      at Object.<anonymous> (node_modules/realm/lib/index.js:125:14)
      at Object.<anonymous> (src/database/db.js:31:25)
      at Object.<anonymous> (src/ethereum/nation.test.js:2:11)
      at next (native)
      at next (native)

 FAIL  src/database/queries.test.js
  ● Test suite failed to run

    TypeError: Cannot redefine property: Worker
        at Function.defineProperty (native)
      
      at Object.<anonymous> (node_modules/realm/lib/index.js:125:14)
      at Object.<anonymous> (src/database/queries.js:4:15)
      at Object.<anonymous> (src/database/queries.test.js:3:16)
      at next (native)
      at next (native)

 FAIL  src/queues/messaging.test.js
  ● Test suite failed to run

    TypeError: Cannot redefine property: Worker
        at Function.defineProperty (native)
      
      at Object.<anonymous> (node_modules/realm/lib/index.js:125:14)
      at Object.<anonymous> (src/database/db.js:31:25)
      at Object.<anonymous> (src/queues/messaging.test.js:1:113)
      at next (native)
      at next (native)

 FAIL  src/queues/transaction.test.js
  ● Test suite failed to run

    TypeError: Cannot redefine property: Worker
        at Function.defineProperty (native)
      
      at Object.<anonymous> (node_modules/realm/lib/index.js:125:14)
      at Object.<anonymous> (src/queues/transaction.js:123:133)
      at Object.<anonymous> (src/queues/transaction.test.js:1:122)
      at next (native)
      at next (native)

 FAIL  src/database/db.test.js
  ● Test suite failed to run

    TypeError: Cannot redefine property: Worker
        at Function.defineProperty (native)
      
      at Object.<anonymous> (node_modules/realm/lib/index.js:125:14)
      at Object.<anonymous> (src/database/db.js:31:25)
      at Object.<anonymous> (src/database/db.test.js:3:11)
      at next (native)
      at next (native)

 FAIL  src/ethereum/wallet.test.js
  ● Test suite failed to run

    TypeError: Cannot redefine property: Worker
        at Function.defineProperty (native)
      
      at Object.<anonymous> (node_modules/realm/lib/index.js:125:14)
      at Object.<anonymous> (src/database/db.js:31:25)
      at Object.<anonymous> (src/ethereum/wallet.js:50:25)
      at Object.<anonymous> (src/ethereum/wallet.test.js:5:15)
      at next (native)
      at next (native)

Test Suites: 6 failed, 5 passed, 11 total
Tests:       53 passed, 53 total
Snapshots:   0 total
Time:        2.819s

```

**Comment by Mnuzz** [comment]
I re-cloned to another folder, ran `npm install` and `npm test` and got the same error but with just two files instead of 5 or 6. `src/database/queries.test.js` and `src/database/db.test.js`.

**Comment by Mnuzz** [comment]
Updating node to version 8.x solved the issue.
